<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" retried="2" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="TestSuite" duration-ms="88986" started-at="2022-07-27T20:02:38 IST" finished-at="2022-07-27T20:04:07 IST">
    <groups>
      <group name="DummyGroup">
        <method signature="LoginTest.Dummy()[pri:1, instance:com.qa.test.LoginTest@1060b431]" name="Dummy" class="com.qa.test.LoginTest"/>
      </group> <!-- DummyGroup -->
    </groups>
    <test name="Testing" duration-ms="88986" started-at="2022-07-27T20:02:38 IST" finished-at="2022-07-27T20:04:07 IST">
      <class name="com.qa.test.LoginTest">
        <test-method status="PASS" signature="initProperties()[pri:0, instance:com.qa.test.LoginTest@1060b431]" name="initProperties" is-config="true" duration-ms="241" started-at="2022-07-27T20:02:37 IST" finished-at="2022-07-27T20:02:38 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initProperties -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.test.LoginTest@1060b431]" name="setUp" is-config="true" duration-ms="8314" started-at="2022-07-27T20:02:38 IST" finished-at="2022-07-27T20:02:46 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setPage()[pri:0, instance:com.qa.test.LoginTest@1060b431]" name="setPage" is-config="true" duration-ms="42" started-at="2022-07-27T20:02:46 IST" finished-at="2022-07-27T20:02:46 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setPage -->
        <test-method status="SKIP" signature="Dummy()[pri:1, instance:com.qa.test.LoginTest@1060b431]" name="Dummy" duration-ms="24" retried="true" started-at="2022-07-27T20:02:46 IST" description="Dummy description" finished-at="2022-07-27T20:02:46 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.qa.test.LoginTest.Dummy(LoginTest.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Dummy -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.test.LoginTest@1060b431]" name="tearDown" is-config="true" duration-ms="967" started-at="2022-07-27T20:02:46 IST" finished-at="2022-07-27T20:02:47 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.test.LoginTest@1060b431]" name="setUp" is-config="true" duration-ms="26512" started-at="2022-07-27T20:02:47 IST" finished-at="2022-07-27T20:03:14 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setPage()[pri:0, instance:com.qa.test.LoginTest@1060b431]" name="setPage" is-config="true" duration-ms="2" started-at="2022-07-27T20:03:14 IST" finished-at="2022-07-27T20:03:14 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setPage -->
        <test-method status="SKIP" signature="Dummy()[pri:1, instance:com.qa.test.LoginTest@1060b431]" name="Dummy" duration-ms="5" retried="true" started-at="2022-07-27T20:03:14 IST" description="Dummy description" finished-at="2022-07-27T20:03:14 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.qa.test.LoginTest.Dummy(LoginTest.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Dummy -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.test.LoginTest@1060b431]" name="tearDown" is-config="true" duration-ms="814" started-at="2022-07-27T20:03:14 IST" finished-at="2022-07-27T20:03:14 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.test.LoginTest@1060b431]" name="setUp" is-config="true" duration-ms="51439" started-at="2022-07-27T20:03:14 IST" finished-at="2022-07-27T20:04:06 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="Dummy()[pri:1, instance:com.qa.test.LoginTest@1060b431]" name="Dummy" duration-ms="0" started-at="2022-07-27T20:04:06 IST" description="Dummy description" finished-at="2022-07-27T20:04:06 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.qa.test.LoginTest.Dummy(LoginTest.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Dummy -->
        <test-method status="PASS" signature="setPage()[pri:0, instance:com.qa.test.LoginTest@1060b431]" name="setPage" is-config="true" duration-ms="0" started-at="2022-07-27T20:04:06 IST" finished-at="2022-07-27T20:04:06 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setPage -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.test.LoginTest@1060b431]" name="tearDown" is-config="true" duration-ms="815" started-at="2022-07-27T20:04:06 IST" finished-at="2022-07-27T20:04:07 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.test.LoginTest -->
    </test> <!-- Testing -->
  </suite> <!-- TestSuite -->
</testng-results>
